// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZUp0Md30ddi2L5QZLr33-WIVNAML0ytE',
    appId: '1:260640434979:web:fdd940dba3ab5be8617a96',
    messagingSenderId: '260640434979',
    projectId: 'tedix-637ca',
    authDomain: 'tedix-637ca.firebaseapp.com',
    storageBucket: 'tedix-637ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWQtv0IM3vWfl2RXT8qOD8zBR83X3FvrE',
    appId: '1:260640434979:android:d937e1ce2b2fc39e617a96',
    messagingSenderId: '260640434979',
    projectId: 'tedix-637ca',
    storageBucket: 'tedix-637ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4qUCVDznj6diP6QpR06OLwyRzhMzpFYM',
    appId: '1:260640434979:ios:0d19aae7f642b0ad617a96',
    messagingSenderId: '260640434979',
    projectId: 'tedix-637ca',
    storageBucket: 'tedix-637ca.firebasestorage.app',
    iosBundleId: 'com.example.tedixdeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4qUCVDznj6diP6QpR06OLwyRzhMzpFYM',
    appId: '1:260640434979:ios:0d19aae7f642b0ad617a96',
    messagingSenderId: '260640434979',
    projectId: 'tedix-637ca',
    storageBucket: 'tedix-637ca.firebasestorage.app',
    iosBundleId: 'com.example.tedixdeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZUp0Md30ddi2L5QZLr33-WIVNAML0ytE',
    appId: '1:260640434979:web:a0c070d122818f4b617a96',
    messagingSenderId: '260640434979',
    projectId: 'tedix-637ca',
    authDomain: 'tedix-637ca.firebaseapp.com',
    storageBucket: 'tedix-637ca.firebasestorage.app',
  );
}
